# GitHub Sponsors funding file

# Uncomment and add your funding options:

# github: [yourusername]  # Replace with up to 4 GitHub Sponsors-enabled usernames
# patreon: yourusername
# open_collective: universal-web3-wallet
# ko_fi: yourusername
# tidelift: npm/universal-web3-wallet
# community_bridge: universal-web3-wallet
# liberapay: yourusername
# issuehunt: yourusername
# otechie: yourusername
# custom: ['https://your-custom-funding-url.com', 'https://another-funding-url.com']

# Crypto funding options (examples):
custom: ['https://donate.universal-web3-wallet.com']

# Instructions for setup:
# 1. Create a GitHub Sponsors account or other funding platform
# 2. Uncomment and update the relevant lines above
# 3. This will add a "Sponsor" button to your repository